### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Aleeexx** [netilon/differify#17]
I would really much appreciate TypeScript support for this package in order to use it safely and easy in my TypeScript application. Could you add TS support?

**Comment by fabian-orue** [comment]
Hi @Aleeexx. Yes, it is something that I will do for the next update.

**Comment by Aleeexx** [comment]
@fabian-orue Awesome, I'm looking forward to it. Do you already know more or less when this update is ready?

**Comment by fabian-orue** [comment]
I think that it will be ready in two weeks aproximately.

**Comment by fabian-orue** [comment]
Hi @Aleeexx, the new version **3.3.0** was released with Typescript support. Regards :)
